services:
  db:
    image: postgres:15
    container_name: golang_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: golang_auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: golang_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_DATABASE: golang_auth
    volumes:
      - .:/app
      - /app/tmp
    depends_on:
      - db

volumes:
  pgdata:
    driver: local    